version: '3'
services:
  api:
    image: ${REGISTRY}/montagu-api:master
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: ${REGISTRY}/montagu-db:master
    ports:
      - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
  orderly:
    image: ${REGISTRY}/orderly.server:master
    ports:
      - "8321:8321"
    volumes:
      - orderly_volume:/orderly
    command: --port 8321 --go-signal /orderly_go /orderly
  orderly_web:
    image: ${REGISTRY}/orderly-web:master
    ports:
      - "8888:8888"
    depends_on:
      - api
    volumes:
      - orderly_volume:/orderly
volumes:
  orderly_volume: